name: Ziggeo Integration Tests
on: [ push, pull_request ]

jobs:
  #  run_tests:
  #    runs-on: macos-latest
  #
  #    strategy:
  #      matrix:
  #        api-level: [ 23 ]
  #        target: [ default ]
  #    steps:
  #      - uses: actions/checkout@v3
  #
  #      - uses: actions/setup-node@master
  #
  #      - uses: actions/setup-java@v3
  #        with:
  #          distribution: 'temurin'
  #          java-version: '11'
  #          cache: 'gradle'
  #
  #      - name: Install node modules
  #        run: |
  #          yarn install
  #
  #      - name: Install cavy
  #        run: yarn global add cavy-cli
  #
  #      - name: Build and test
  #        uses: reactivecircus/android-emulator-runner@v2
  #        with:
  #          api-level: ${{ matrix.api-level }}
  #          target: ${{ matrix.target }}
  #          profile: Nexus 4
  #          script: "cavy run-android --file index.js"

  publish_release:
    runs-on: macos-latest
    #    needs: run_tests
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@master

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: clean
        run: yarn cache clean

      - name: Install node modules
        run: |
          yarn install

      - name: Create google services file
        run: cat /Users/runner/work/ReactNativeDemo/ReactNativeDemo/android/app/google-services.json | base64
      - name: Putting google services data
        env:
          DATA: ${{ secrets.PLAY_CONFIG_JSON }}
        run: echo $DATA > /Users/runner/work/ReactNativeDemo/ReactNativeDemo/android/app/google-services.json

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: z_release_keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

      - name: Publish APK test
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.ziggeo.reactnativesdk.demo
          releaseFiles: android/app/build/outputs/apk/release/androidRN-release.apk
          track: internal
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.33

